language: node_js
os: osx
branches:
  only:
  - master
  - /^deploy-.*$/
node_js:
  - 10
install:
  - npm install
script:
  - npm test

deploy:
  provider: npm
  email: 1197252996@qq.com
  api_key: $NPM_TOKEN
  on:
    branch: master
  skip-cleanup: true